# Generated by Django 5.0.6 on 2025-09-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iotcore", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edgedata",
            name="quality",
            field=models.IntegerField(choices=[(1, "GOOD"), (0, "BAD")], default=1),
        ),
    ]
